apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: mycontainer
        image: "wededo4644/save2drive:4"
        ports:
        - containerPort: 3000
